### ISSUE TITLE
Remove explicit population of GHRepository.parent since github-api now does this

### ISSUE THREAD

**Issue by justinharringa** [salesforce/dockerfile-image-update#158]
#155 brings in version 1.112 of `github-api` which fixes the following issue:
https://github.com/hub4j/github-api/pull/821/files

This is the relevant code (check to see if there are other references): https://github.com/salesforce/dockerfile-image-update/blob/4a5ee1679fb16c43e22e7c7e544a72aa0f3dc408/dockerfile-image-update/src/main/java/com/salesforce/dockerfileimageupdate/process/GitHubPullRequestSender.java#L50-L52

**Comment by RaviTezu** [comment]
Hi @justinharringa I would like to take this up.
