### ISSUE TITLE
Handle cases where there are more than 1000 downstream consumers of an image

### ISSUE THREAD

**Issue by justinharringa** [salesforce/dockerfile-image-update#169]
GitHub Search [limits results to 1000 results per search](https://developer.github.com/v3/search/#about-the-search-api) but will give you the full total. We'll need a new strategy to deal with those instances where our [code search](https://developer.github.com/v3/search/#search-code) has too many results.

Some potential opportunities:
* split up searches to handle searches by org(s) when we know we have more than 1000 (create a set of targets)
  * potentially partition
* silly idea: if less than 2000 just sort ascending then descending which likely has further dragons and doesn't scale

Definitely should log this case so that it's obvious that we're missing some repos. This would be a hint that this should be run in a more scalable manner.

**Comment by afalko** [comment]
There is no way to return paginated search?

**Comment by npwolf** [comment]
Searching around, the way people have looked to get around this is by creating narrower search criteria, like slicing dates https://stackoverflow.com/q/37602893/13943777 . Doesn't appear to be any great solutions.

**Comment by justinharringa** [comment]
Paginated search ends at 1000 (or 1020 if you leave the default). The date ranges don't work for code search (that example is for repository searches).

**Comment by justinharringa** [comment]
Note that it would be possible to run this as a service if you can more efficiently store who the downstream consumers are and then just run the `child` command. That being said, it might be nice to somehow intelligently split out once we hit 1000 results but it seems that there are ultimately scaling limits in relying on GitHub search.

**Comment by justinharringa** [comment]
Another potential fix to this would be for DFIU to try and do a best effort split of the orgs it finds if it found more than 1000.

Essentially:
```
orgsToExclude = []
while searchResults.length() > 1000
    orgWithMostHits = getOrgWithMostHits(searchResults)
    runDFIUForOrg(orgWithMostHits)
    orgsToExclude.add(orgWithMostHits)
    searchResults = getNewSearchResults(orgsToExclude)
```
