### ISSUE TITLE
Image name with "-" in registry name not working

### ISSUE THREAD

**Issue by ksrisurapaneni** [salesforce/dockerfile-image-update#210]
**Describe the bug**

Inconsistency in search methods across tool code is causing issues when using more complex image names and not letting it work as intended. For ex:

Looks like the tool finds the image and creates a PR successfully when the image is as follows:
```
FROM rv-python-runtime:1.0.0
```

But it doesn't find the image or create a PR  when the image is as follows:
```
FROM xyz-asndnkdk-ffwwwsw-deeeereer.jfrog.io/rv-python-runtime:1.0.0
```

**To Reproduce**

Add this line to a test Dockerfile:

```
FROM xyz-asndnkdk-ffwwwsw-deeeereer.jfrog.io/rv-python-runtime:1.0.0
```

Case 1: Run below command with image name as-is:

```
docker run --rm  -e git_api_token -e git_api_url salesforce/dockerfile-image-update:1.0.131 -o <org> -b main parent "xyz-asndnkdk-ffwwwsw-deeeereer.jfrog.io/rv-python-runtime" 1.0.1 image_tag_store
```

Because the search is using Github API, it doesn't find the image name:

```
[main] INFO com.salesforce.dockerfileimageupdate.subcommands.impl.Parent - Finding Dockerfiles with the given image...
[main] INFO com.salesforce.dockerfileimageupdate.utils.DockerfileGitHubUtil - Number of files found for xyz-asndnkdk-ffwwwsw-deeeereer.jfrog.io/rv-python-runtime:0
```

Case 2: Replace dashes with spaces when running the below command:

```
docker run --rm  -e git_api_token -e git_api_url salesforce/dockerfile-image-update:1.0.131 -o <org> -b main parent "xyz asndnkdk ffwwwsw deeeereer.jfrog.io/rv python runtime" 1.0.1 image_tag_store
```

Since the tool initially uses Github API, the search works on replacing the "-"s with spaces. But looks like the forking process doesn't use github API and uses Java substring, so it goes on to fail then because it isn't able to find the image name with spaces in it and returns thhe below error:

```
[main] INFO com.salesforce.dockerfileimageupdate.utils.DockerfileGitHubUtil - Number of files found for xyz asndnkdk ffwwwsw deeeereer.jfrog.io/rv python runtime:2
[main] INFO com.salesforce.dockerfileimageupdate.process.GitHubPullRequestSender - Forking repositories...
[main] WARN com.salesforce.dockerfileimageupdate.process.GitHubPullRequestSender - Skipping <org>/foo because didn't find the image 'xyz asndnkdk ffwwwsw deeeereer.jfrog.io/rv python runtime' which required an update in path Dockerfile
```

**Expected behavior**

Ideally, we want such an image name search to work fine and create PRs. Currently, this is not possible with the tool.

**Additional context**

**Comment by ksrisurapaneni** [comment]
@justinharringa : Please check above.

**Comment by justinharringa** [comment]
Welcome and thanks for the detailed description! This is really helpful! Yeah, it seems that we may need to do some treatment of the registry in this case due to dashes. This seems somewhat related to #191 with multiple slashes.

**Comment by ksrisurapaneni** [comment]
Yeah, in this case, it is not multiple slashes; but a mix of dashes and dots.

https://github.com/craftcms/cms/issues/3080

**Comment by justinharringa** [comment]
Yeah, sorry I wasn't clear. Definitely agree that this is a separate search issue. 😄 

The problem with this solution is that you'd be expanding the search space which then starts to quickly run up against #169 (the 1000 search result limit). So including the registry helps to keep that somewhat narrow. Definitely agree that we should potentially look to GraphQL to see if it can help with both the 1000 search result limit and potentially improve how search works. Have you tried to see if this query works properly in GraphQL?

**Comment by ksrisurapaneni** [comment]
I haven't tried GraphQL actually, since it looks like that would need me to change quite a lot of code. Do you think you have time this fix to play with this? :)

**Comment by ksrisurapaneni** [comment]
@justinharringa : Found a better solution that looks for registry/image. Below is the code:

```
if(query.contains("-")) {
query = query.replace('-', ' ');
}
```

These two lines need to be added before line 83. Please let me know if you want me to create a PR for this. I tested it locally and it works perfectly.

https://github.com/salesforce/dockerfile-image-update/blob/master/dockerfile-image-update/src/main/java/com/salesforce/dockerfileimageupdate/utils/DockerfileGitHubUtil.java#L83-L84

**Comment by justinharringa** [comment]
It turns out that a query like this works well: 
`org:justinharringa this registry has dashes.somecompany.io/rv-python-runtime`
https://github.com/search?q=org%3Ajustinharringa+this+registry+has+dashes.somecompany.io%2Frv-python-runtime&type=code

It finds: https://github.com/justinharringa/somecontainers/blob/639aa492ce264d42a2c13ccc01702bab8101bcd1/Dockerfile.dashing

**Comment by ksrisurapaneni** [comment]
@justinharringa : Looks like this issue isn't resolved!
