### ISSUE TITLE
Unable to find image when there is a "." in the image name

### ISSUE THREAD

**Issue by ksrisurapaneni** [salesforce/dockerfile-image-update#217]
**Describe the bug**
Thank you for fixing #210. `salesforce/dockerfile-image-update:1.0.132` now works with "-" in the registry name. But looks like is unable to find when there is a "." in the image name. 

Looks like the tool finds the image and creates a PR successfully when the image is as follows:

```
FROM xyz-asndnkdk-ffwwwsw-deeeereer.jfrog.io/rv-python-3-runtime:1.0.0
```

But it doesn't find the image or create a PR when the image is as follows:

```
FROM xyz-asndnkdk-ffwwwsw-deeeereer.jfrog.io/rv-python-3.9-runtime:1.0.0
```

**To Reproduce**

Add this line to a test Dockerfile:

```
FROM xyz-asndnkdk-ffwwwsw-deeeereer.jfrog.io/rv-python-3.9-runtime:1.0.0
```

Run below command with image name as-is:
```
docker run --rm  -e git_api_token -e git_api_url salesforce/dockerfile-image-update:1.0.132 -o <org> -b main parent "xyz-asndnkdk-ffwwwsw-deeeereer.jfrog.io/rv-python-3.9-runtime" 1.0.1 image_tag_store
```

Error:

```
[main] INFO com.salesforce.dockerfileimageupdate.subcommands.impl.Parent - Finding Dockerfiles with the given image...
[main] INFO com.salesforce.dockerfileimageupdate.utils.DockerfileGitHubUtil - Number of files found for xyz-asndnkdk-ffwwwsw-deeeereer.jfrog.io/rv-python-3.9-runtime:0
```

**Expected behavior**
Ideally, we want such an image name search to work fine and create PRs. Currently, this is not possible with the tool.

The error again seems to be because the search is using Github API, it can't find the image name with "." in it. Can you please fix this? It will be really helpful, all our new images have this convention and will carry a ".".

Thanks,
Keerti

**Comment by justinharringa** [comment]
Hi Keerti,

  I suspect this is an issue with the mixture of dashes and dots in the image name in GitHub Code Search. I'm aware of underscores and dots working well in GitHub Search (e.g. I suspect `rv_python_3.9_runtime` would work if images were named as such). While that doesn't really help your case unless you were to change your naming standard, I just wanted to document my thoughts/observations for readers here. 

  I'm not sure when I'll have time to poke at this. 

Hope all is well!

**Comment by ksrisurapaneni** [comment]
Hi @justinharringa , my colleague created a rough PR which works but is not really ideal since it replaces the dots in both registry name and image name (which might extend the search). But this should give you a rough idea to work on.

Please let me know if you have any questions at all.

https://github.com/salesforce/dockerfile-image-update/pull/240

Thanks,
Keerti
