### ISSUE TITLE
Add support for custom files to update

### ISSUE THREAD

**Issue by npars** [salesforce/dockerfile-image-update#236]
**Is your feature request related to a problem? Please describe.**
The image updater currently only catches image tags that are in Dockerfiles in our repo. It would be nice if it also updated
docker-compose files so that we would not need to manually push commits to the PRs that the tool creates.

**Describe the solution you'd like**
Add ability to search for and update docker-compose yaml files in a addition to Dockerfiles. A basic search might be
something like: `language:yaml filename:docker-compose "image: docker/image/name"`. This will miss files that don't
follow the docker-compose file name convention, but that's probably better than searching _all_ yaml files.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by afalko** [comment]
I'm changing the subject to allow us to pass a list of files we want to scan vs. only supporting Dockerfiles

**Comment by afalko** [comment]
Also while we do this, we should consider supporting wild cards:
`Dockerfile-*`

**Comment by justinharringa** [comment]
We already scan all `Dockerfile` by virtue of using `filename:Dockerfile` and it will find, for example `Dockerfile-somethingelse`

**Comment by justinharringa** [comment]
I believe you'll need to be somewhat specific about parsing / file format as well.
