### ISSUE TITLE
-o or --org doesnt work with all and parent command

### ISSUE THREAD

**Issue by vishmegh88** [salesforce/dockerfile-image-update#28]

**Comment by afalko** [comment]
Are you getting an error message @vishmegh88 ? Here is an example, I currenly have running: https://github.com/afalko/alpine-java/blob/master/Jenkinsfile#L35

Is your token the same user as the org by any chance?

**Comment by vishmegh88** [comment]
@afalko No token user is not the same and there is not error message, but its searching in the org out side given org and creating pulls request.

Prima facie, I see that problem is fetching argument parser ns.get("o") is returning null despite org being passed. Please have a look.

**Comment by vishmegh88** [comment]
I think it fails as ns,get("o") should be ns.get("org") . As Argument parser puts org as key in namespace. Same applies to -b.

**Comment by vishmegh88** [comment]
@justinharringa I am trying to run similar command but still tool was picking up repos outside provided git org. 

I have created the PR fixing this:
https://github.com/salesforce/dockerfile-image-update/pull/30

Also have shared the scenario with @afalko
