### ISSUE TITLE
Regression: Existing PRs are closed and new PRs are created instead of adding commits to existing PRs

### ISSUE THREAD

**Issue by afalko** [salesforce/dockerfile-image-update#32]
@jdoshi1 Your change made new commits close existing PRs and create a new one instead of each commit. Was this intended?

**Comment by jdoshi1** [comment]
Yes. I'm closing existing PRs since contents of the parent can change i.e. Dockerfile can move to a new folder and it would essentially make the old PR stale. If I don't delete the stale PR, this repo will be skipped forever.

**Comment by jdoshi1** [comment]
Link to the comment where the existing PR is deleted before re-forking and creating new PR - 
https://github.com/salesforce/dockerfile-image-update/blob/master/dockerfile-image-update/src/main/java/com/salesforce/dockerfileimageupdate/utils/DockerfileGitHubUtil.java#L43
