### ISSUE TITLE
NPE while fetching content in parent command

### ISSUE THREAD

**Issue by vishmegh88** [salesforce/dockerfile-image-update#34]
version: 1.0.7

Getting NPE when running parent command. Could be because of below code in DockerfileGithubUtil.modifyAllOnGithub. If the issue is happening even after sleep, atleast we should handle gracefully. Also can we increase the wait time so that this doesn't happen. 

/* There are issues with the GitHub API returning that the GitHub repository exists, but has no content,
         * when we try to pull on it the moment it is created. The system must wait a short time before we can move on.
         */
        for (int i = 0; i < 5; i++) {
            try {
                tree = repo.getDirectoryContent(".", branch);
                break;

Command: java -jar ./dockerfile-image-update.jar -g https://********.com/api/v3/ -m 'Automatic Dockerfile Image Updater' parent image*** tag**** store****

0:15:35.730 [main] [INFO] com.salesforce.dockerfileimageupdate.subcommands.impl.Parent - Fixing Dockerfiles in org/repo...
20:15:35.788 [main] [WARN] com.salesforce.dockerfileimageupdate.utils.GitHubUtil - Content in repository not created yet. Retrying connection to fork...
20:15:36.837 [main] [WARN] com.salesforce.dockerfileimageupdate.utils.GitHubUtil - Content in repository not created yet. Retrying connection to fork...
20:15:37.886 [main] [WARN] com.salesforce.dockerfileimageupdate.utils.GitHubUtil - Content in repository not created yet. Retrying connection to fork...
20:15:38.940 [main] [WARN] com.salesforce.dockerfileimageupdate.utils.GitHubUtil - Content in repository not created yet. Retrying connection to fork...
20:15:39.994 [main] [WARN] com.salesforce.dockerfileimageupdate.utils.GitHubUtil - Content in repository not created yet. Retrying connection to fork...
20:15:41.050 [main] [WARN] com.salesforce.dockerfileimageupdate.utils.GitHubUtil - Content in repository not created yet. Retrying connection to fork...
20:15:42.107 [main] [WARN] com.salesforce.dockerfileimageupdate.utils.GitHubUtil - Content in repository not created yet. Retrying connection to fork...
20:15:43.157 [main] [WARN] com.salesforce.dockerfileimageupdate.utils.GitHubUtil - Content in repository not created yet. Retrying connection to fork...
20:15:44.219 [main] [WARN] com.salesforce.dockerfileimageupdate.utils.GitHubUtil - Content in repository not created yet. Retrying connection to fork...
20:15:45.269 [main] [WARN] com.salesforce.dockerfileimageupdate.utils.GitHubUtil - Content in repository not created yet. Retrying connection to fork...
Exception in thread "main" java.lang.NullPointerException
	at com.salesforce.dockerfileimageupdate.utils.DockerfileGitHubUtil.modifyOnGithub(DockerfileGitHubUtil.java:133)
	at com.salesforce.dockerfileimageupdate.subcommands.impl.Parent.changeDockerfiles(Parent.java:174)
	at com.salesforce.dockerfileimageupdate.subcommands.impl.Parent.execute(Parent.java:63)
	at com.salesforce.dockerfileimageupdate.CommandLine.main(CommandLine.java:52)

**Comment by jdoshi1** [comment]
Issue has been fixed in version 1.0.14
Let us know if this is still a problem and we can re-visit it. Thanks.
