### ISSUE TITLE
Does this work with private registries as well?

### ISSUE THREAD

**Issue by 030** [salesforce/dockerfile-image-update#76]
According the README, this tool is suitable for images that reside on Github. Would it work in conjunction with quay.io as well?

**Comment by afalko** [comment]
It will work with any registry; github private or public is the only limitation. Git lab is not supported yet.

**Comment by justinharringa** [comment]
@030 note that this tool acts on the `Dockerfile` itself so that's why any registry would work. The idea is that it would send an update PR and trigger a PR flow on the child image.

**Comment by justinharringa** [comment]
I hope that helped clear things up @030. I'll go ahead and close this out for now.
